jobs:
  include:
    - stage: Build
      name: Tests
      language: elixir
      elixir: '1.9.1'
      otp_release: '22.0.7'
      services:
        - postgresql
        - redis-server
      cache:
        directories:
          - deps
          - _build
      env:
        - MIX_ENV=test
      before_script: mix ecto.reset
      script: mix do compile --warnings-as-errors, coveralls.json
      after_success: bash <(curl -s https://codecov.io/bash)

    - name: Build
     language: minimal
     script: docker build --build-arg SECRET_KEY_BASE --build-arg GUARDIAN_SECRET --build-arg PLAID_CLIENT_ID --build-arg PLAID_SECRET_KEY --build-arg PLAID_PUBLIC_KEY -t us.gcr.io/cloud-57/spendable-api:latest .
