jobs:
  include:
  - stage: Build
    name: Tests
    language: elixir
    elixir: 1.10
    otp_release: 22.0.7
    services:
    - postgresql
    - redis-server
    cache:
      directories:
      - deps
      - _build
      - "$HOME/google-cloud-sdk/"
    env:
    - MIX_ENV=test
    before_script: mix ecto.reset
    script: mix do compile --warnings-as-errors, coveralls.json
    after_success: bash <(curl -s https://codecov.io/bash)
  - name: Build
    if: branch = master
    language: minimal
    before_script:
      - if [ ! -d "$HOME/google-cloud-sdk" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
      - gcloud components update
      - source $HOME/google-cloud-sdk/path.bash.inc
      - cat gcloud-credentials.json | docker login -u _json_key --password-stdin https://us.gcr.io
      - docker pull us.gcr.io/cloud-57/spendable-api:latest
    script:
      - docker build
        --build-arg DB_PASSWORD
        --build-arg GUARDIAN_SECRET
        --build-arg PLAID_CLIENT_ID
        --build-arg PLAID_PUBLIC_KEY
        --build-arg PLAID_SECRET_KEY
        --build-arg SECRET_KEY_BASE
        --cache-from us.gcr.io/cloud-57/spendable-api:latest
        -t us.gcr.io/cloud-57/spendable-api:latest .
    after_success: docker push us.gcr.io/cloud-57/spendable-api:latest
  - stage: Deploy
    if: branch = master
    name: Deploy
    before_script:
      - gcloud auth activate-service-account --key-file gcloud-credentials.json
      - gcloud config set project cloud-57
    script:
      - gcloud compute instance-groups managed rolling-action replace spendable-api
        --region=us-central1
        --max-unavailable 0
        --max-surge 3
before_install:
- openssl aes-256-cbc -K $encrypted_b62a425c5f3b_key -iv $encrypted_b62a425c5f3b_iv
  -in gcloud-credentials.json.enc -out gcloud-credentials.json
  -d
