matrix:
  include:
    - language: elixir
      elixir: '1.9.1'
      otp_release: '22.0.7'
      script: mix test

    - language: minimal
      script: docker build -t us.gcr.io/cloud-57/budget-api:latest .
      
#language: elixir
#elixir:
#  - '1.9.1'
#otp_release:
#  - '22.0.7'
#services:
#  - postgresql
#  - redis-server
#  - docker
#cache:
#  directories:
#    - deps
#    - _build
#jobs:
#  include:
#    - script: mix test
#    - script: docker build -t us.gcr.io/cloud-57/budget-api:latest .
#      #if: branch = master
