language: elixir
elixir:
  - '1.9.1'
otp_release:
  - '22.0.7'
services:
  - postgresql
  - redis-server
cache:
  directories:
    - deps
    - _build
jobs:
  include:
    - script: mix test
    - script: mix release
