version: '3.7'

services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD:
    volumes:
      - postgres-data:/var/lib/mysql
    ports:
      - "5432:5432"
    logging:
      driver: none

volumes:
  postgres-data:
