nameOverride: spendable-web
replicaCount: 1

service:
  port: 80
  targetPort: 8080
  type: ClusterIP
  # the health check must fail 3 times before we will recreate it
  livenessProbe:
    httpGet:
      path: /
      port: http
    failureThreshold: 6
    periodSeconds: 10
  # give the pod 5 minutes to run migrations on startup
  startupProbe:
    httpGet:
      path: /
      port: http
    failureThreshold: 30
    periodSeconds: 10
  # check every second to see if we should send traffic to a pod
  readinessProbe:
    httpGet:
      path: /
      port: http
    periodSeconds: 5

ingressroute:
  domain: app.spendable.money
  path: "/"

resources:
  requests:
    cpu: 20m
    memory: 32M
  limits:
    cpu: "1"
    memory: 256M

envVars: {}

