nameOverride: spendable
replicaCount: 2

imagePullSecrets:
  - name: github-docker-auth

migrations:
  run: true
  command: [./bin/spendable, eval, Spendable.Release.migrate()]

workloadIdentity:
  enabled: true

service:
  targetPort: 4000
  routes:
    - domain: spendable.money

resources:
  requests:
    cpu: 250m
  limits:
    memory: 1G

envVars:
  DB_HOSTNAME: aero.blue
  DB_USERNAME: spendable

