nameOverride: spendable
replicaCount: 1

service:
  port: 80
  targetPort: 4000
  type: ClusterIP
  # the health check must fail 3 times before we will recreate it
  livenessProbe:
    httpGet:
      path: /_health
      port: http
    failureThreshold: 6
    periodSeconds: 10
  # give the pod 5 minutes to run migrations on startup
  startupProbe:
    httpGet:
      path: /_health
      port: http
    failureThreshold: 30
    periodSeconds: 10
  # check every second to see if we should send traffic to a pod
  readinessProbe:
    httpGet:
      path: /_health
      port: http
    periodSeconds: 5

ingressroute:
  domain: spendable.money
  path: "/"

imagePullSecrets:
  - name: "gcr-json-key"

resources:
  requests:
    cpu: 50m
    memory: 64M
  limits:
    cpu: "1"
    memory: 256M

envVars:
  DB_HOSTNAME: 10.122.112.3
  DB_USERNAME: postgres

