name: Deploy
on:
  push:
    branches:
      - deploy

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@main

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: cloud-57
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: GCP Authentication
        run: |
          gcloud auth configure-docker us.gcr.io
          gcloud container clusters get-credentials default-cluster --zone us-central1-a

      - name: Decode APNS Files
        env:
          APNS_CERT: ${{ secrets.APNS_CERT }}
          APNS_KEY: ${{ secrets.APNS_KEY }}
        run: |        
          mkdir priv/apns
          echo "$APNS_CERT" | base64 -d > priv/apns/cert.pem
          echo "$APNS_KEY" | base64 -d > priv/apns/key_unencrypted.pem

      - name: Build
        run: |    
          docker pull us.gcr.io/cloud-57/spendable-api:latest    
          docker build \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg GUARDIAN_SECRET=${{ secrets.GUARDIAN_SECRET }} \
            --build-arg PLAID_CLIENT_ID=${{ secrets.PLAID_CLIENT_ID }} \
            --build-arg PLAID_PUBLIC_KEY=${{ secrets.PLAID_PUBLIC_KEY }} \
            --build-arg PLAID_SECRET_KEY=${{ secrets.PLAID_SECRET_KEY }} \
            --build-arg SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} \
            --build-arg SENTRY_DSN=${{ secrets.SENTRY_DSN }} \
            --cache-from us.gcr.io/cloud-57/spendable-api:latest \
            -f .devops/Dockerfile \
            -t us.gcr.io/cloud-57/spendable-api:${GITHUB_SHA} \
            -t us.gcr.io/cloud-57/spendable-api:latest \
            .
          docker push us.gcr.io/cloud-57/spendable-api

      - name: Setup Helm
        run: |
          helm plugin install https://github.com/hayorov/helm-gcs.git
          helm repo add cloud-57 gs://cloud-57-helm
          helm repo update

      - name: Rollout Deploy
        run: |
          helm upgrade --install spendable cloud-57/cloud-57 \
          -f .devops/helm/values.yaml \
          --set image.repository=us.gcr.io/cloud-57/spendable-api \
          --set image.tag=${GITHUB_SHA} \
          -n backend
          kubectl rollout status --watch deployment spendable -n backend