name: Deploy
on:
  push:
    branches:
      - master
      - self-hosted

jobs:
  backend:
    name: Backend
    runs-on: [self-hosted, Linux, ARM64]

    defaults:
      run:
        working-directory: backend

    env:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    steps:
      - uses: actions/checkout@main

      - name: Setup kube config
        run: |
          mkdir $HOME/.kube
          touch $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "$KUBE_CONFIG" > $HOME/.kube/config

      - name: Docker Login
        run: |    
          docker login registry.fiftyseven.media --username ${{ secrets.BASIC_AUTH_USERNAME }} --password ${{ secrets.BASIC_AUTH_PASSWORD }}

      - name: Build
        run: |    
          CACHE_IMAGE=registry.fiftyseven.media/spendable-api:$(sha256sum mix.exs mix.lock config/config.exs config/prod.exs | sha256sum  | awk '{ print $1 }')
          docker pull $CACHE_IMAGE
          
          docker build \
          --cache-from $CACHE_IMAGE \
          -t registry.fiftyseven.media/spendable-api:${GITHUB_SHA} \
          -t $CACHE_IMAGE \
          -f .devops/Dockerfile .

      - name: Push
        run: |
          docker push registry.fiftyseven.media/spendable-api:${GITHUB_SHA} 
          docker push $CACHE_IMAGE 

      - name: Setup Helm
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push.git
          helm repo add cloud-57 https://helm.fiftyseven.media --username ${{ secrets.BASIC_AUTH_USERNAME }} --password ${{ secrets.BASIC_AUTH_PASSWORD }}
          helm repo update

      - name: Rollout Deploy
        run: |
          helm upgrade --install spendable cloud-57/cloud-57 \
          -f .devops/helm/values.yaml \
          --version v1.0.2 \
          --set image.repository=registry.fiftyseven.media/spendable-api \
          --set image.tag=${GITHUB_SHA} \
          -n backend
          kubectl rollout status --watch deployment spendable -n backend
