name: Deploy
on:
  push:
    branches:
      - deploy
    paths:
    - 'backend/**'

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    env:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/mix.exs', '**/mix.lock', '**/config/config.exs', '**/config/prod.exs') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          context: backend
          file: backend/.devops/Dockerfile
          platforms: linux/arm64
          push: true
          tags: us.gcr.io/cloud-57/spendable-api:${{ github.sha }}

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Setup kube config
        run: |
          mkdir $HOME/.kube
          touch $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "$KUBE_CONFIG" > $HOME/.kube/config

      - name: Setup Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Rollout Deploy
        run: |
          helm upgrade spendable cloud-57/cloud-57 \
          -f .devops/helm/values.yaml \
          --version v1.0.2 \
          --namespace backend \
          --set image.repository=us.gcr.io/cloud-57/spendable-api \
          --set image.tag=${GITHUB_SHA} \
          --atomic \
          --debug

