name: Deploy
on:
  push:
    branches:
      - wireguard

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
      DOCKER_HOST: ssh://build@192.168.5.181
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      WIREGUARD_CONF: ${{ secrets.WIREGUARD_CONF }}

    steps:
      - uses: actions/checkout@main

      - name: Connect to Private Network
        run: |
          sudo apt-get -y install wireguard openresolv
          echo "$WIREGUARD_CONF" | sudo tee -a /etc/wireguard/wg0.conf
          wg-quick up wg0
          mkdir ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.5.181 >> ~/.ssh/known_hosts
          
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: cloud-57
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: GCP Authentication
        run: |
          gcloud auth configure-docker us.gcr.io

      - name: Build
        run: |    
          docker pull us.gcr.io/cloud-57/spendable-api:build || true
          docker pull us.gcr.io/cloud-57/spendable-api:latest || true
          docker buildx build \
            --target build \
            --cache-from us.gcr.io/cloud-57/spendable-api:build \
            -t us.gcr.io/cloud-57/spendable-api:build \
            -f .devops/Dockerfile .
          docker buildx build \
            --cache-from us.gcr.io/cloud-57/spendable-api:build \
            --cache-from us.gcr.io/cloud-57/spendable-api:latest \
            -t us.gcr.io/cloud-57/spendable-api:${GITHUB_SHA} \
            -t us.gcr.io/cloud-57/spendable-api:latest \
            -f .devops/Dockerfile .
          docker push us.gcr.io/cloud-57/spendable-api

      - name: Setup Helm
        run: |
          helm plugin install https://github.com/hayorov/helm-gcs.git
          helm repo add cloud-57 gs://cloud-57-helm
          helm repo update

      - name: Rollout Deploy
        run: |
          echo "$KUBE_CONFIG" > ~/.kube/config
          helm upgrade --install spendable cloud-57/cloud-57 \
          -f .devops/helm/values.yaml \
          --version v1.0.2 \
          --set image.repository=us.gcr.io/cloud-57/spendable-api \
          --set image.tag=${GITHUB_SHA} \
          -n backend
          kubectl rollout status --watch deployment spendable -n backend