name: Deploy
on: workflow_dispatch

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    env:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: backend
          file: backend/.devops/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Setup kube config
        run: |
          mkdir $HOME/.kube
          touch $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "$KUBE_CONFIG" > $HOME/.kube/config

      - name: Setup Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Rollout Deploy
        run: |
          helm upgrade spendable cloud-57/cloud-57 \
          -f .devops/helm/values.yaml \
          --version v1.0.2 \
          --namespace backend \
          --set image.repository=ghcr.io/michaelst/spendable \
          --set image.tag=${GITHUB_SHA} \
          --atomic \
          --debug

