name: Deploy
on:
  push:
    branches:
      - master
      - deploy

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-$(sha256sum mix.exs mix.lock config/config.exs config/prod.exs | sha256sum  | awk '{ print $1 }')
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.fiftyseven.media
          username: ${{ secrets.BASIC_AUTH_USERNAME }}
          password: ${{ secrets.BASIC_AUTH_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          context: .
          file: .devops/Dockerfile
          platforms: linux/arm64
          push: true
          tags: registry.fiftyseven.media/spendable-api:${{ github.sha }}

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # - name: Setup kube config
      #   run: |
      #     mkdir $HOME/.kube
      #     touch $HOME/.kube/config
      #     chmod 600 $HOME/.kube/config
      #     echo "$KUBE_CONFIG" > $HOME/.kube/config
 
      # - name: Setup Helm
      #   run: |
      #     curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      #     helm plugin install https://github.com/chartmuseum/helm-push.git
      #     helm repo add cloud-57 https://helm.fiftyseven.media --username ${{ secrets.BASIC_AUTH_USERNAME }} --password ${{ secrets.BASIC_AUTH_PASSWORD }}
      #     helm repo update

      # - name: Rollout Deploy
      #   run: |
      #     helm upgrade --install spendable cloud-57/cloud-57 \
      #     -f .devops/helm/values.yaml \
      #     --version v1.0.2 \
      #     --set image.repository=registry.fiftyseven.media/spendable-api \
      #     --set image.tag=${GITHUB_SHA} \
      #     --atomic \
      #     --debug \
      #     -n backend
          
