name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "web/**"

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: backend
          file: backend/.devops/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-api:${{ github.sha }}

  web:
    name: Web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: web
          file: web/.devops/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-web:${{ github.sha }}
