name: Tests
on: push

jobs:
  wireguard:
    runs-on: ubuntu-20.04

    env:
      DOCKER_HOST: ssh://build@192.168.5.181
      WIREGUARD_CONF: ${{ secrets.WIREGUARD_CONF }}


    steps:
      - run: 'echo "$WIREGUARD_CONF" > wg0.conf'

      - run: |
          apt install wireguard
          wg-quick up wg0.conf
          docker info
          wg-quick down wg0.conf

  backend:
    name: Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env: 
      TEST_DB_PASSWORD: postgres
      MIX_ENV: test

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-elixir@master
        with:
          otp-version: 22.3.3
          elixir-version: 1.10.3

      - name: Cache Backend Deps
        uses: actions/cache@master
        with:
          path: backend/deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/backend/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache Backend Build
        uses: actions/cache@master
        with:
          path: backend/_build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/backend/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: mix do deps.get, compile --warnings-as-errors, ecto.reset
      - run: mix coveralls.json

      - uses: codecov/codecov-action@master

  credo:
    name: Credo
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env: 
      MIX_ENV: test

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-elixir@master
        with:
          otp-version: 22.3.3
          elixir-version: 1.10.3

      - name: Cache Backend Deps
        uses: actions/cache@master
        with:
          path: backend/deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/backend/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache Backend Build
        uses: actions/cache@master
        with:
          path: backend/_build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/backend/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: mix do deps.get, compile --warnings-as-errors
      - run: mix credo
